### ISSUE TITLE
Logout all seems to delete all tokens but user still can access authorized route /users?

### ISSUE THREAD

**Issue by MikeMnD** [Onix-Systems/nest-js-boilerplate#23]
In short how do i invalidate/delete all access tokens for a user on the server so any new request should have a "token expired" response.
At the moment after logout, or logout all - a request with old bearer token is still valid.

Also in the redis store i see that the email/refresh token pair is deleted.

**Comment by v-checha** [comment]
@MikeMnD Hello, the JWT is stored on browser, so remove the token deleting the cookie at client side.

If you need also to invalidate the token from server side before its expiration time, for example account deleted/blocked/suspended, password changed, permissions changed, user logged out by admin.
or use the same strategy with **black list** like we implemented for refresh token. 

Thanks.

**Comment by MikeMnD** [comment]
Thanks, a bit late but none the less I went with minimal info in the token and other caching mechanism.
Other than that the "black list like we implemented for refresh token" is a working solution although i wen for another.
