### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by Oyinkansolight** [Onix-Systems/nest-js-boilerplate#40]
Hello really great work here! I am using an M1 Mac and after having to force install node modules npm run start:dev does not work which is a separate issue and I then try the docker-compose up command also and get this below. I think it's just the git installation that is the issue.

oyinkay@Oyinkansolas-MacBook-Air momo-backend % docker-compose up
Building app
[+] Building 6.9s (10/11)                                                  
 => [internal] load build definition from App.Dockerfile              0.1s
 => => transferring dockerfile: 41B                                   0.0s
 => [internal] load .dockerignore                                     0.0s
 => => transferring context: 2B                                       0.0s
 => [internal] load metadata for docker.io/library/node:16-slim       2.5s
 => [auth] library/node:pull token for registry-1.docker.io           0.0s
 => [internal] load build context                                     3.5s
 => => transferring context: 4.98MB                                   3.1s
 => [1/6] FROM docker.io/library/node:16-slim@sha256:3c8acd4934617f6  0.0s
 => CACHED [2/6] WORKDIR /var/www/app                                 0.0s
 => CACHED [3/6] RUN apt-get update                                   0.0s
 => CACHED [4/6] COPY . .                                             0.0s
 => ERROR [5/6] RUN apt-get install -y git                            0.7s
------
 > [5/6] RUN apt-get install -y git:
#10 0.651 Reading package lists...
#10 0.657 Building dependency tree...
#10 0.658 Reading state information...
#10 0.658 E: Unable to locate package git
------
executor failed running [/bin/sh -c apt-get install -y git]: exit code: 100
ERROR: Service 'app' failed to build : Build failed

**Comment by v-checha** [comment]
@Oyinkansolight Hello, please try next steps :
`docker system prune`
then again:
`docker-compose up -d`

more info please see at the next [issue](https://stackoverflow.com/questions/62473932/atleast-one-invalid-signature-was-encountered) 
Thanks.

**Comment by Oyinkansolight** [comment]
Thank you. Will check it out.

**Comment by v-checha** [comment]
Close that issue, let me know if you need something else. Thank you.
